server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cloudmusic?characterEncoding=utf-8&&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      initial-size: 20
      max-idle: 20
      min-idle: 10
      default-auto-commit: true
      min-evictable-idle-time-millis: 3600000
  servlet:
    multipart:
      max-file-size: 2MB

logging:
  level:
    com:
      example:
        demo:
          dao: debug

mybatis:
  config-location: classpath:mybatis.cfg.xml

file:
  upload-dir: /material-music-resource

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
