server:
  port: 8080
  servlet:
    context-path: /api

# 数据库
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/materialmusic?characterEncoding=utf-8&&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      initial-size: 20
      max-idle: 20
      min-idle: 10
      default-auto-commit: true
      min-evictable-idle-time-millis: 3600000
  servlet:
    multipart:
      max-file-size: 2MB

# redis
redis:
  host: localhost
  port: 6379
  max-wait: 30000
  max-active: 100
  max-idle: 20
  min-idle: 0
  timeout: 3000

# 日志
logging:
  level:
    com:
      example:
        demo:
          dao: debug

mybatis:
  config-location: classpath:mybatis.cfg.xml

# 资源目录
file:
  upload-dir: /material-music-resource

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
