name: material-music CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install npm dependencies
      run: cd material-music-app && npm install
    - name: Run build task
      run: cd material-music-app && npm run build --if-present
    - name: Deploy to Server
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        METHOD: sftp
        PORT: ${{ secrets.FTP_PORT }}
        LOCAL_DIR: material-music-app/build
        REMOTE_DIR: /root/html/metarial-music/material-music-app
        ARGS: --delete --verbose --continue

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: cd material-music-server && mvn -B package --file pom.xml
    - name: Deploy to Server
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        METHOD: sftp
        PORT: ${{ secrets.FTP_PORT }}
        LOCAL_DIR: material-music-server/target
        REMOTE_DIR: /root/html/metarial-music/material-music-server
        ARGS: --delete --verbose --continue